
homeassistant:
  name: Death Star
  latitude: !secret homelocation_lat
  longitude: !secret homelocation_long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  packages: !include_dir_named packages/

        
default_config:
# HTTP #
http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
#enables a map showing the location of tracked devices
map:
#browser_mod:
python_script:
#alexa
api:




#systemhealth
mobile_app:
system_health:
ffmpeg:
#integrations
wake_on_lan:
#includes





#    _____ _____ ____  _   _ _  _____    _____ ____  _   _ ______ _____ _____ 
#   |  __ \_   _/ __ \| \ | ( )/ ____|  / ____/ __ \| \ | |  ____|_   _/ ____|
#   | |  | || || |  | |  \| |/| (___   | |   | |  | |  \| | |__    | || |  __ 
#   | |  | || || |  | | . ` |  \___ \  | |   | |  | | . ` |  __|   | || | |_ |
#   | |__| || || |__| | |\  |  ____) | | |___| |__| | |\  | |     _| || |__| |
#   |_____/_____\____/|_| \_| |_____/   \_____\____/|_| \_|_|    |_____\_____|
#                                                                             
#                                                   
#inputs
input_datetime: !include includes/input_datetimes.yaml
input_number: !include includes/input_numbers.yaml
input_boolean: !include includes/input_boolean.yaml
input_text: !include includes/input_text.yaml
input_select: !include includes/input_select.yaml
# Logging and history
logger: !include includes/logger.yaml
recorder: !include includes/recorder.yaml
device_tracker: !include includes/device_trackers.yaml

#merge list still need to move to 1 file
sensor: !include_dir_merge_list includes/sensor/


script: !include_dir_merge_named includes/scripts/


# Others:
automation: !include_dir_merge_list automations/
alexa: !include includes/alexa.yaml
binary_sensor: !include includes/binary_sensors.yaml
group: !include includes/groups.yaml
person: !include includes/persons.yaml
homekit: !include includes/homekit.yaml
fan: !include includes/fan.yaml
discovery: !include includes/discovery.yaml
proximity: !include includes/proximity.yaml
light: !include includes/lights.yaml
notify: !include includes/notify.yaml
camera: !include includes/camera.yaml
ios: !include includes/ios.yaml
switch: !include includes/switches.yaml
scene: !include includes/scenes.yaml
shell_command: !include includes/shell_commands.yaml
calendar: !include includes/calander.yaml
octoprint: !include includes/octoprint.yaml
weather: !include includes/weather.yaml
speedtestdotnet: !include includes/speedtestdotnet.yaml
nzbget: !include includes/nzbget.yaml
tado: !include includes/tado.yaml
zoneminder: !include includes/zoneminder.yaml
