#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
- platform: template
  sensors:
    someone_showering:
      friendly_name: Someone is showering
      value_template: >
        {{ states("sensor.douche_2") | float(0) > 85 }}
     
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.woonkamer_sensor_motion", "on")
            or is_state("binary_sensor.keuken_sensor_motion", "on")
            or is_state("binary_sensor.gang_sensor_motion", "on")
            or is_state("binary_sensor.wc_sensor_motion", "on")
            or is_state("binary_sensor.overloop_sensor_motion", "on")
            or is_state("binary_sensor.douche_sensor_motion", "on") }}


    activity_outside_bedroom:
      friendly_name: Activity outside the bedroom
      value_template: >
        {{ is_state("binary_sensor.woonkamer_sensor_motion", "on")
            or is_state("binary_sensor.keuken_sensor_motion", "on")
            or is_state("binary_sensor.gang_sensor_motion", "on")
            or is_state("binary_sensor.wc_sensor_motion", "on")
            or is_state("binary_sensor.overloop_sensor_motion", "on")
            or is_state("binary_sensor.douche_sensor_motion", "on")
            or is_state("binary_sensor.kantoor_sensor_motion", "on")
            or is_state("media_player.55pus8503_12", "on") }}
      delay_off: "00:01:00"  
    activity_office:
      friendly_name: Office Activity
      value_template: >
       {{ is_state("binary_sensor.kantoor_sensor_motion", "on")}}
      delay_off: "00:01:00"

#wasmachine      
    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ states("sensor.wasmachine_power") | float(0) > 3 }}
      delay_off: "00:05:00"
      icon_template: >
        {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
    dryer_machine:
      friendly_name: Dryer
      value_template: >
        {{ states("sensor.droger_power") | float(0) > 3 }}
      delay_off: "00:03:00"
      icon_template: >
        {% if is_state("binary_sensor.dryer_machine", "on") %}
          mdi:tumble-dryer
        {% else %}
          mdi:tumble-dryer-off
        {% endif %}
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.dion", "home")
            and not is_state("person.mandie", "home") }}
    worked_enough_today:
      friendly_name: Worked enough today
      value_template: >
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:work