#       _ _                 _
#   ___| (_)_ __ ___   __ _| |_ ___
#  / __| | | '_ ` _ \ / _` | __/ _ \
# | (__| | | | | | | | (_| | ||  __/
#  \___|_|_|_| |_| |_|\__,_|\__\___|
#
#
- alias: "Climate: turn on the heating 30 min before waking up"
  trigger:
    platform: time
    at: "06:30:00"
  condition:
    condition: state
    entity_id:
      - input_boolean.automatic_temperature
    state: "on"
  action:
    - service: script.set_high_temperature
    - service: script.set_water_temperature

- alias: "Climate: turn on the heating when going home"
  trigger:
    platform: numeric_state
    entity_id: proximity.home
    below: 6
    above: 1
  condition:
    - condition: state
      entity_id: input_boolean.automatic_temperature
      state: "on"
    - condition: time
      after: "16:00:00"
      before: "22:00:00"
    - "{{ is_state_attr('proximity.home', 'dir_of_travel', 'towards') }}"
    - "{{ not is_state_attr('climate.heating', 'temperature', states('input_number.temperature_high')) }}"
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
  action:
    - service: script.set_high_temperature
    - service: notify.all_iphones
      data:
        title: "Climate"
        message: "Automatically turned on the heating 🥵℃"  
        
- alias: "Climate: turn off the heating at 22:00"
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.automatic_temperature
      state: "on"
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "off"
    - "{{ not is_state_attr('climate.heating', 'temperature', states('input_number.temperature_low')|float) }}"
  action:
    - service: script.set_low_temperature
    - service: notify.all_iphones
      data:
        message: "Turned off the heating 🥶, click to turn it on again?"
        data:
          push:
            badge: 0
            category: turn_on_heating
            
- alias: "Climate: turn on heating again after notification"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_ON_HEATING
  action:
    service: script.set_high_temperature        
    
- alias: "Climate: Turn off heating on weekdays when Mandie is gone and Dion is working from home"
  trigger:
    - entity_id: person.mandie
      from: home
      platform: state
      to: not_home  
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - thu
    - condition: time
      after: "08:30:00"    
      before: "15:00:00"
    - condition: state
      entity_id: person.dion
      state: home
  action: 
  - service: climate.set_temperature
    entity_id: climate.woonkamer
    data:
      temperature: "17"
  - service: climate.set_temperature
    entity_id: climate.eetkamer
    data:
      temperature: "17"
  - service: climate.set_temperature
    entity_id: climate.lukes_kamer
    data:
      temperature: "17"
  - service: climate.set_temperature
    entity_id: climate.slaapkamer
    data:
     temperature: "17"
  - service: climate.set_temperature
    entity_id: climate.gang
    data:
      temperature: "20"
  - service: climate.set_temperature
    entity_id: climate.douche
    data:
      temperature: "17"      
  - service: climate.set_temperature
    entity_id: climate.kantoor
    data:
     temperature: "20"

- alias: "Climate: Pre heat Luke's bedroom"
  trigger: 
    - platform: time
      at: "18:45:00"
  condition:
    - condition: state
      entity_id: group.family_status
      state: home
  action: 
    - service: climate.set_temperature
      entity_id: climate.lukes_kamer
      data:
        temperature: 20
    - service: notify.all_iphones
      data:
        title: "Climate"
        message: "Preheating Luke's bedroom to 20℃"  
