#    ____ _____ _   _          _______     _______ ______ _   _  _____  ____  _____   _____ 
#   |  _ \_   _| \ | |   /\   |  __ \ \   / / ____|  ____| \ | |/ ____|/ __ \|  __ \ / ____|
#   | |_) || | |  \| |  /  \  | |__) \ \_/ / (___ | |__  |  \| | (___ | |  | | |__) | (___  
#   |  _ < | | | . ` | / /\ \ |  _  / \   / \___ \|  __| | . ` |\___ \| |  | |  _  / \___ \ 
#   | |_) || |_| |\  |/ ____ \| | \ \  | |  ____) | |____| |\  |____) | |__| | | \ \ ____) |
#   |____/_____|_| \_/_/    \_\_|  \_\ |_| |_____/|______|_| \_|_____/ \____/|_|  \_\_____/ 
#                                      ______                                               
#
- platform: template
  sensors:
    someone_showering:
      friendly_name: Someone is showering
      value_template: >
        {{ states("sensor.douche_2") | float(0) > 85 }}
     
    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.woonkamer_sensor_motion", "on")
            or is_state("binary_sensor.keuken_sensor_motion", "on")
            or is_state("binary_sensor.gang_sensor_motion", "on")
            or is_state("binary_sensor.wc_sensor_motion", "on")
            or is_state("binary_sensor.overloop_sensor_motion", "on")
            or is_state("binary_sensor.douche_sensor_motion", "on") }}


    activity_outside_bedroom:
      friendly_name: Activity outside the bedroom
      value_template: >
        {{ is_state("binary_sensor.woonkamer_sensor_motion", "on")
            or is_state("binary_sensor.keuken_sensor_motion", "on")
            or is_state("binary_sensor.gang_sensor_motion", "on")
            or is_state("binary_sensor.wc_sensor_motion", "on")
            or is_state("binary_sensor.overloop_sensor_motion", "on")
            or is_state("binary_sensor.douche_sensor_motion", "on")
            or is_state("binary_sensor.kantoor_sensor_motion", "on")
            or is_state("media_player.55pus8503_12", "on") }}
      delay_off: "00:01:00"  
    activity_office:
      friendly_name: Office Activity
      value_template: >
       {{ is_state("binary_sensor.kantoor_sensor_motion", "on")}}
      delay_off: "00:01:00"

#wasmachine      
    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ states("sensor.wasmachine_power") | float(0) > 3 }}
      delay_off: "00:05:00"
      icon_template: >
        {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
    dryer_machine:
      friendly_name: Dryer
      value_template: >
        {{ states("sensor.droger_power") | float(0) > 3 }}
      delay_off: "00:03:00"
      icon_template: >
        {% if is_state("binary_sensor.dryer_machine", "on") %}
          mdi:tumble-dryer
        {% else %}
          mdi:tumble-dryer-off
        {% endif %}
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.dion", "home")
            and not is_state("person.mandie", "home") }}
    worked_enough_today:
      friendly_name: Worked enough today
      value_template: >
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:work 
#powerstates
- platform: template
  sensors:
    washer_on:
      friendly_name: "Wasmachine aan"
      device_class: power
      delay_off: 
        minutes: 5
      value_template: >
        {{ states('sensor.wasmachine_power')| float > 50 }}
    dryer_on:
      friendly_name: "Droger aan"
      device_class: power
      delay_off:
        minutes: 2
      value_template: >
        {{ states('sensor.droger_power')| float > 50}}
    tv_on:
      friendly_name: "TV aan"
      device_class: power
      value_template: >
       {{ states('sensor.tv_power')| float > 75}}
#sleeptime
- platform: tod
  name: 'sleep_time'
  after: '23:00'
  before: '7:00'
#bayesian sensor
- platform: 'bayesian'
  name: in_bed_bayesian
  prior: 0.6
  probability_threshold: 0.65
  observations:
    - entity_id: 'binary_sensor.sleep_time'
      prob_given_true: 0.7
      platform: 'state'
      to_state: 'on'
    - entity_id: 'group.woonkamer_verlichting'
      prob_given_true: 0.6
      platform: 'state'
      to_state: 'off'
    - entity_id: 'mediaplayer.tv'
      prob_given_true: 0.7
      platform: 'state'
      to_state: 'off'         
#hygrostat
- platform: generic_hygrostat
  name: badkamer Hygrostat
  sensor: sensor.douche_2
  delta_trigger: 3
  target_offset: 3 
  max_on_time: 7200 