#-
#
#   ___ __ _ _ __ ___   ___ _ __ __ _
#  / __/ _` | '_ ` _ \ / _ \ '__/ _` |
# | (_| (_| | | | | | |  __/ | | (_| |
#  \___\__,_|_| |_| |_|\___|_|  \__,_|
#
#
- platform: mjpeg
  name: Ender3
  still_image_url: !secret ender3_cam_snapshot
  mjpeg_url: !secret ender3_cam_stream