# UnRAID Sensors v1.2

## UnRAID Version Sensor URLs
### Stable URL: https://s3.amazonaws.com/dnld.lime-technology.com/stable/unRAIDServer.plg
### Beta URL: https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg

#- platform: command_line
#  name: Unraid Version (Next)
#  command: /usr/bin/curl --insecure "https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg" 2>&1 | grep Version |awk '{print $3}'


## API sensors

## HDD SNMP Temperatures

- platform: snmp
  name: 'UnRAID DISK1 Temperature'
  host: !secret unraid_ip
  port: 161
  community: public
  version: 2c
  baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1
  accept_errors: false
  value_template: >
    {{ value.split(':')[1].strip() }}
  unit_of_measurement: 'C'

- platform: snmp
  name: 'UnRAID DISK2 Temperature'
  host: !secret unraid_ip
  port: 161
  version: 2c
  community: public
  baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1 
  accept_errors: false
  value_template: >
    {{ value.split(':')[1].strip() }}
  unit_of_measurement: 'C'


## SNMP LAN Upload

- platform: snmp
  name: 'UnRAID LAN0 Upload'
  host: !secret unraid_ip
  port: 161
  community: public
  baseoid: .1.3.6.1.2.1.2.2.1.16.9 
  accept_errors: false
  unit_of_measurement: "Kbps"
  value_template: >
    {{((value | float ) / 1000000 ) | round(2) }}


## SNMP LAN Download

- platform: snmp
  name: 'UnRAID LAN0 Download (VLAN10)'
  host: !secret unraid_ip
  port: 161
  community: public
  baseoid: .1.3.6.1.2.1.2.2.1.10.9 
  accept_errors: false
  unit_of_measurement: "Kbps"
  value_template: >
    {{((value | float ) / 1000000 ) | round(2) }}
