# friends of hue woonkamer knop 1 toggle
- alias: SWITCH - woonkamer knop een
  trigger: 
    platform: event
    event_type: deconz_event
    event_data:
      id: woonkamer
      event: 1000
  action:
    - service: broadlink.send
      data:
        host: !secret broadlink_Woonkamer
        packet: 'JgBUASUNKw0NKg8oDygOKg8oDygOKQ8pDikPAAEDKQ4qDQ4qDSoOKSoNKw0pDisMKw0pDiroKQ4rDA4qDygPKCsMDioPKA8oDiopDiroKg0qDQ8pDikOKSsNDikOKQ4pDiopDiroKg0qDQ4qDikOKSsMDykPKA4pDiopDiroKg0qDQ4qDSoOKSsMDioPKA4pDioqDSrnKg4pDg4pDioPKCoNDioPKA8oDikrDSrnKw0qDQ4pDioOKSsMDioOKQ4pDykpDiroKQ4qDQ4pDioOKSoNDioOKQ8oDioqDSroKg0qDQ4qDSoOKSsMDioOKQ4pDykqDSrnKw0qDQ4pDioPKCsMDykOKQ4pDykpDivlLA0qDQ4pDykOKSsMDioOKQ4pDikqDinoKw0pDg4pDykNKikODikPKQ4pDikrDSnoKwwqDg4pDygOKSsNDikPKA4qDSopDioADQUAAAAA'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.woonkamer_fan_state
    - service: fan.turn_on
      data:
        entity_id: fan.woonkamer_fan
        speed: Min
# friends of hue woonkamer knop 2 toggle
- alias: SWITCH - woonkamer knop twee
  trigger: 
    platform: event
    event_type: deconz_event
    event_data:
      id: woonkamer
      event: 2000
  action:
    - service: broadlink.send
      data:
        host: !secret broadlink_Woonkamer
        packet: 'JgA2ASQOKg0OKg4pDygOKQ4qDikOKQ4pDioOAAEDKw0pDg8oDioOKSoNKg4pDioNKwwqDiroKg0qDQ8pDSoPKA4pDioOKQ4pKw0OKQ8AAQMqDSoNDioOKQ8oDioOKQ4pDioqDQ8oDgABBCoNKg4OKQ4pDygOKg4pDikPKSoNDikOAAEEKwwrDQ4pDikOKg4pDygPKA4qKQ4OKQ8AAQMqDSsNDygOKQ4qDikOKQ4qDikrDA4qDQABBCsNKQ4OKQ4qDikOKQ4qDikOKSoODikOAAEEKg0qDQ8pDSoOKQ4qDSoOKQ4pKw0OKQ4AAQQpDisMDioOKQ8oDioOKQ4pDygrDQ4pDgABBCoNKw0NKg4pDikOKg4pDikPKCsNDygOAAEEKQ4qDQ4pDioPKA8oDygOKg4pKwwPKQ8ADQUAAA=='
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.woonkamer_fan_state
    - service: fan.turn_on
      data:
        entity_id: fan.woonkamer_fan
        speed: Med
# friends of hue woonkamer knop 3 toggle
- alias: SWITCH - woonkamer knop drie
  trigger: 
    platform: event
    event_type: deconz_event
    event_data:
      id: woonkamer
      event: 3000
  action:
    - service: broadlink.send
      data:
        host: !secret broadlink_Woonkamer
        packet: 'JgDcACUNKw0NKg4pDikPKQ4pDygOKQ8pDikOAAEDKg4qDQ4pDioOKSoNKg0qDioNKg0rDSnoKwwqDg4pDikOKg0qDikOKQ8pDikPKCroKQ4rDA4qDikPKA4pDykNKg8oDikPKSrnKg4pDg4pDikPKQ4pDikOKg0qDygPKCroKwwrDQ4pDikOKQ4qDikOKQ8oDioOKSvnKg0qDQ4qDygOKQ4pDioPKA4pDioNKinpKg0qDQ4pDioPKA4pDykOKQ4pDikOKirnKg4qDQ8oDikOKg4pDikPKA4qDygOKSoADQUAAAAAAAAAAAAAAAA='
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.woonkamer_fan_state
    - service: fan.turn_on
      data:
        entity_id: fan.woonkamer_fan
        speed: Max
# friends of hue woonkamer knop 4 toggle
- alias: SWITCH - woonkamer knop vier
  trigger: 
    platform: event
    event_type: deconz_event
    event_data:
      id: woonkamer
      event: 4000
  action:
    - service: broadlink.send
      data:
        host: !secret broadlink_Woonkamer
        packet: 'JgCeASQOKg0OKQ4qDikOKQ8oDykOKQ4pDygOAAEEKwwqDg4pDikOKikOKg0qDSoOKQ4qDSroKg0qDg4pDygOKg4pDikqDQ8pDikPKA4AAQQrDCoODygOKQ4pDioPKCsMDioOKQ8oDgABBCsMKg0OKg4pDygPKQ4pKg0OKQ4qDygOAAEEKQ4qDQ4qDikOKQ8pDSopDg4pDioOKQ4AAQQpDioNDioPKA8oDygOKioNDikOKg4pDgABBCkOKg0OKQ8pDikPKA4qKQ4OKQ8oDioPAAEBKw4qDQ4pDioOKQ4pDikqDg8oDygOKg4AAQMqDikODikPKQ4pDikOKSoODikOKQ8pDgABAyoOKg0OKQ4qDikOKQ4pKw0OKQ8oDioOAAEDKg4pDg4pDioOKQ4pDikrDQ4pDikOKg4AAQMqDikODikOKQ4qDikOKSoODikOKQ4pDgABBCoOKg0OKQ4pDykOKQ4pKw0NKg4pDygOAAEEKg0rDQ4pDikOKQ4qDikpDg8oDioOKQ8AAQMpDioNDykNKg4pDygOKioNDygOKQ8pDQANBQAAAAAAAAAAAAA='
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.woonkamer_fan_state
    - service: fan.turn_off
      data:
        entity_id: fan.woonkamer_fan
