#    ________                     .__               ___ ___      ___.    
#   /  _____/  ____   ____   ____ |  |   ____      /   |   \ __ _\_ |__  
#  /   \  ___ /  _ \ /  _ \ / ___\|  | _/ __ \    /    ~    \  |  \ __ \ 
#  \    \_\  (  <_> |  <_> ) /_/  >  |_\  ___/    \    Y    /  |  / \_\ \
#   \______  /\____/ \____/\___  /|____/\___  >____\___|_  /|____/|___  /
#          \/             /_____/           \/_____/     \/           \/ 
#                                                                        
#
- alias: "Google Hub: Restart catt every 9 minutes"
  trigger: 
    - platform: time_pattern
      minutes: "/9"
  condition:  
    condition: or
    conditions:
      - condition: state
        entity_id: group.family_status
        state: 'home'
      - condition: state
        entity_id: input_boolean.homemode_guest
        state: 'on'
  action:
#  - service: media_player.volume_mute
#    entity_id: media_player.nesthub8796
  - service: shell_command.cast_ha_woonkamer  
  - service: media_player.volume_set
    data:
      entity_id: media_player.nesthub8796
      volume_level: 25
# Not home or night time
- alias: "Google Hub: Not home or night time"
  trigger:
  - platform: state
    entity_id: group.family_status
    to: 'not_home'
  - platform: state
    entity_id: binary_sensor.sleep_time
    to: 'on'
  condition:  
    condition: or
    conditions:
      - condition: state
        entity_id: group.family_status
        state: 'not_home'
      - condition: state
        entity_id: binary_sensor.sleep_time
        state: 'on'
  action:
  - service: shell_command.cast_ha_woonkamer_stop

   
   